'use server'

import { z } from 'zod'
import { createItem } from '@directus/sdk'
import { getDirectusClient } from '@/lib/directus/client'

const institutionContactSchema = z.object({
    institution_name: z.string().min(2, { message: 'El nombre de la institución debe tener al menos 2 caracteres' }),
    institution_type: z.enum(['fundacion', 'ong', 'asociacion', 'otro'], {
        message: 'Selecciona un tipo de institución válido'
    }),
    contact_name: z.string().min(2, { message: 'El nombre de contacto debe tener al menos 2 caracteres' }),
    position: z.string().min(2, { message: 'El cargo debe tener al menos 2 caracteres' }),
    email: z.string().email({ message: 'Email inválido' }),
    phone: z.string().min(8, { message: 'El teléfono debe tener al menos 8 caracteres' }),
    website: z.string().url({ message: 'URL inválida' }).optional().or(z.literal('')),
    description: z.string().min(50, { message: 'La descripción debe tener al menos 50 caracteres' }),
    activities: z.string().min(50, { message: 'Las actividades deben tener al menos 50 caracteres' }),
    instagram: z.string().optional(),
    facebook: z.string().optional(),
    linkedin: z.string().optional(),
})

export async function sendInstitutionContact(prevState: any, formData: FormData) {
    console.log('[v0] Starting institution contact form submission via Directus...')

    const validatedFields = institutionContactSchema.safeParse({
        institution_name: formData.get('institution_name'),
        institution_type: formData.get('institution_type'),
        contact_name: formData.get('contact_name'),
        position: formData.get('position'),
        email: formData.get('email'),
        phone: formData.get('phone'),
        website: formData.get('website'),
        description: formData.get('description'),
        activities: formData.get('activities'),
        instagram: formData.get('instagram'),
        facebook: formData.get('facebook'),
        linkedin: formData.get('linkedin'),
    })

    if (!validatedFields.success) {
        console.log('[v0] Validation failed:', validatedFields.error.flatten().fieldErrors)
        return {
            success: false,
            errors: validatedFields.error.flatten().fieldErrors,
            message: 'Por favor revisa los campos del formulario',
        }
    }

    const data = validatedFields.data

    try {
        const client = getDirectusClient() as any

        // Create the item in Directus
        // Note: The collection 'contacto_instituciones' must exist in Directus
        // and the Public role (or the token user) must have create permissions
        await client.request(createItem('contacto_instituciones', {
            nombre_institucion: data.institution_name,
            tipo_institucion: data.institution_type,
            nombre_contacto: data.contact_name,
            cargo: data.position,
            email: data.email,
            telefono: data.phone,
            sitio_web: data.website || null,
            descripcion: data.description,
            actividades: data.activities,
            instagram: data.instagram || null,
            facebook: data.facebook || null,
            linkedin: data.linkedin || null,
            estado: 'pendiente'
            // date_created is auto-generated by Directus
        }))

        console.log('[v0] Institution contact saved to Directus successfully')

        return {
            success: true,
            message: '¡Gracias por contactarnos! Hemos recibido tu información y nos pondremos en contacto contigo pronto para coordinar la publicación de tus actividades.',
        }
    } catch (error) {
        console.error('[v0] Error saving institution contact to Directus:', error)
        return {
            success: false,
            message: 'Hubo un error al enviar el formulario. Por favor intenta nuevamente.',
        }
    }
}
